markdown: redcarpet
highlighter: pygments
exclude: [publish.sh, README.md, Gemfile, Gemfile.lock]

name: nbeloglazov blog
description: Quil, Clojure and programming in general
url: http://nbeloglazov.com

